import streamlit as st
import datetime
import time
from ai_suggester import get_code_suggestions, ask_code_question
from code_parser import parse_code
from error_detector import detect_errors
from style_checker import show_style_corrected
import difflib
import re

def extract_corrected_code(ai_text):
    """Extracts the python code block from the AI response."""
    # Pattern to find "Improved Code", start of python block, and then capture until:
    # 1. A closing code block (```)
    # 2. The start of the next section (## Detailed Explanations or similar)
    # 3. End of string
    pattern = r"## Improved Code\s*```python\n(.*?)(?=\n```|\n##|\Z)"
    match = re.search(pattern, ai_text, re.DOTALL)
    if match:
        return match.group(1).strip()
    
    # Fallback: look for the last python block
    patterns = re.findall(r"```python\n(.*?)(?=\n```|\n##|\Z)", ai_text, re.DOTALL)
    if patterns:
        return patterns[-1].strip()
    return None

def generate_diff_view(original, modified):
    """Generates a side-by-side HTML diff."""
    d = difflib.HtmlDiff(wrapcolumn=None, tabsize=4)
    html = d.make_file(
        original.splitlines(), 
        modified.splitlines(), 
        fromdesc="Original", 
        todesc="Suggested Fix",
        context=True, 
        numlines=3
    )
    # Custom CSS for Dark Mode Diff
    custom_css = """
    <style>
        .diff {
            font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
            font-size: 14px;
            width: 100%;
            background-color: #0d1117; /* GitHub Dark Dimmed bg */
            color: #c9d1d9;
            border-radius: 8px;
            border: 1px solid #30363d;
            border-spacing: 0;
            overflow: hidden;
        }
        .diff td {
            padding: 2px 10px;
            vertical-align: top;
            white-space: pre; /* Keep code formatting */
        }
        .diff th {
            background-color: #161b22;
            color: #f0f6fc;
            text-align: left;
            padding: 8px 10px;
            border-bottom: 1px solid #30363d;
        }
        .diff_next, .diff_header {
            background-color: #161b22;
            color: #8b949e;
            border: none;
            width: 1%; /* Auto-shrink line number columns */
            white-space: nowrap;
            text-align: right;
            user-select: none;
        }
        /* Added lines */
        .diff_add {
            background-color: rgba(46, 160, 67, 0.15); /* GitHub Green tint */
            color: #e6ffec;
        }
        span.diff_add {
            background-color: rgba(46, 160, 67, 0.4);
        }
        /* Deleted lines */
        .diff_sub {
            background-color: rgba(218, 54, 51, 0.15); /* GitHub Red tint */
            color: #ffebe9;
        }
        span.diff_sub {
            background-color: rgba(218, 54, 51, 0.4);
            text-decoration: none; /* Removed strikethrough for cleaner look */
        }
        /* Changed lines */
        .diff_chg {
            background-color: rgba(210, 153, 34, 0.15); /* GitHub Yellow tint */
        }
        span.diff_chg {
            background-color: rgba(210, 153, 34, 0.4);
        }
        a { color: inherit; text-decoration: none; }
        /* Hide the Legend/Summary tables generated by difflib */
        table[summary="Colors"], table[summary="Links"] { display: none; }
     </style>
    """
    return custom_css + html

def stream_data(text):
    """Yields text word by word for the typewriter effect."""
    for word in text.split(" "):
        yield word + " "
        # time.sleep(0.002) # Removed delay for faster output

def setup_page():
    """Configures the Streamlit page settings and Custom CSS."""
    # Custom CSS
    st.markdown("""
<style>
    /* Main Background */
    .stApp {
        background: linear-gradient(to bottom right, #0F172A, #1E1B4B); 
        color: #E2E8F0;
    }
    
    /* Sidebar */
    section[data-testid="stSidebar"] {
        background-color: #0B0F19;
        border-right: 1px solid #334155;
    }

    /* Headers */
    .main-header {
        font-size: 3rem;
        font-weight: 800;
        background: -webkit-linear-gradient(45deg, #A78BFA, #38BDF8);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 10px;
    }
    
    .sub-header {
        font-size: 1.2rem;
        color: #94A3B8;
        margin-bottom: 30px;
        font-family: 'Segoe UI', sans-serif;
    }
    
    /* Input Area */
    .stTextArea textarea {
        background-color: #1E293B !important;
        color: #F8FAFC !important;
        border: 1px solid #475569;
        border-radius: 12px;
    }
    
    /* Buttons */
    div.stButton > button {
        background: linear-gradient(90deg, #6366F1 0%, #8B5CF6 100%);
        color: white;
        border: none;
        padding: 12px 28px;
        border-radius: 8px;
        font-weight: 600;
        transition: all 0.3s ease;
    }
    div.stButton > button:hover {
        transform: scale(1.02);
        box-shadow: 0 4px 15px rgba(139, 92, 246, 0.4);
    }
    
    /* Metrics */
    div[data-testid="stMetricValue"] {
        color: #38BDF8;
    }
    
    /* Chat Messages */
    .stChatMessage {
        background-color: #1E293B;
        border-radius: 10px;
        margin-bottom: 10px;
    }
</style>
""", unsafe_allow_html=True)

def render_sidebar():
    """Renders the sidebar and returns the selected navigation page."""
    with st.sidebar:
        st.markdown("### Code Reviewer")
        st.markdown("Made by Riddhima ")
        
        if st.button("🔄 Refresh App"):
            st.rerun()
        
        st.markdown("---")
        
        # Navigation
        st.caption("MENU")
        page = st.radio(
            "Navigation",
            ["✨ Code Studio", "📊 Insights & Report", "📜 History"],
            label_visibility="collapsed"
        )
        
        st.markdown("---")
        
        # Configuration
        st.caption("SETTINGS")
        st.selectbox("Language", ["Python"], index=0)
        
        st.caption("ANALYSIS DEPTH")
        col_s1, col_s2 = st.columns(2)
        with col_s1:
            st.checkbox("Security", value=True)
            st.checkbox("Logic", value=True)
        with col_s2:
            st.checkbox("Style", value=True)
            st.checkbox("Bugs", value=True)
            
        st.markdown("---")
        if st.button("🗑️ Clear History"):
            st.session_state.history = []
            st.rerun()
            
    return page

def render_code_studio():
    """Renders the Code Studio page."""
    st.markdown('<div class="main-header">Code Studio</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Review, Optimize, and Secure your code in seconds.</div>', unsafe_allow_html=True)

    if "code_input" not in st.session_state:
        st.session_state.code_input = ""

    col_input, col_action = st.columns([3, 1])
    with col_input:
        st.markdown("#### 📥 Input Source")
    
    code_input = st.text_area("Write or paste your code here...", height=450, value=st.session_state.code_input)
    st.session_state.code_input = code_input

    col_btn1, col_btn2, col_spacer = st.columns([1, 1, 3])
    with col_btn1:
        # Dynamic button label
        btn_label = "🔄 Regenerate Analysis" if st.session_state.get("ai_review") else "🚀 Analyze Now"
        if st.button(btn_label):
            if code_input.strip():
                with st.spinner("🔮 Consulting the AI ...."):
                    # Initialize states
                    st.session_state.errors = None
                    st.session_state.static_warnings = []
                    st.session_state.style_result = None
                    
                    # 1. Parse Code (Checks for Syntax Errors)
                    parse_result = parse_code(code_input)
                    
                    if not parse_result["success"]:
                        # Syntax Error found!
                        error_details = parse_result["error"]
                        error_msg = f"Syntax Error at line {error_details['line']}: {error_details['message']}\nCode: {error_details['text']}"
                        st.session_state.errors = error_msg
                        st.error(error_msg)
                    else:
                        # 2. If Syntax is Valid, Check for Static Warnings (Unused Vars)
                        static_check = detect_errors(code_input)
                        if static_check["success"] and static_check["errors"]:
                            st.session_state.static_warnings = static_check["errors"]

                        # 3. Check Style
                        style_check = show_style_corrected(code_input)
                        if style_check["success"]:
                             st.session_state.style_result = style_check["corrected_code"]

                        # 4. Get AI Review
                        review = get_code_suggestions(code_input)
                        st.session_state.ai_review = review
                        st.session_state.chat_history = [] 
                        
                        # Add to History
                        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                        if "history" not in st.session_state:
                             st.session_state.history = []
                             
                        st.session_state.history.insert(0, {
                            "timestamp": timestamp,
                            "code": code_input,
                            "review": review,
                            "errors": st.session_state.errors,
                            "warnings": st.session_state.static_warnings
                        })
                        
                        st.success("Analysis Ready! Switch to the **Insights** tab.")
            else:
                st.warning("Please provide some code first.")
    with col_btn2:
        if st.button("🧹 Clear Workspace"):
            st.session_state.code_input = ""
            st.session_state.chat_history = []
            st.rerun()

def render_insights_report():
    """Renders the Insights & Report page."""
    st.markdown('<div class="main-header">Analysis Report</div>', unsafe_allow_html=True)
    
    if "ai_review" in st.session_state and st.session_state.ai_review:
        
        # Determine Status
        status_label = "Healthy"
        status_delta = "+1"
        status_color = "normal"
        
        if st.session_state.errors:
            status_label = "Broken"
            status_delta = "-5"
            status_color = "inverse"
        elif st.session_state.get("static_warnings"):
            status_label = "Issues Found"
            status_delta = "-2"
            status_color = "inverse"

        # Metrics
        c1, c2, c3 = st.columns(3)
        with c1:
            st.metric("Status", status_label, delta=status_delta, delta_color=status_color)
        with c2:
            warning_count = len(st.session_state.get("static_warnings", []))
            st.metric("Static Issues", str(warning_count), delta_color="inverse")
        with c3:
             st.metric("AI Model", "Zephyr-7B")

        st.markdown("---")
        
        # Display Syntax Errors
        if st.session_state.errors:
            st.error(f"❌ **Code Parsing Failed**\n\n{st.session_state.errors}")

        # Display Static Warnings (Unused Vars)
        warnings = st.session_state.get("static_warnings", [])
        if warnings:
            with st.expander("⚠️ Static Code Analysis Issues", expanded=True):
                for w in warnings:
                    st.warning(f"**{w['type']}**: {w['message']}")
                    st.caption(f"Suggestion: {w['suggestion']}")

        tab_main, tab_style, tab_chat = st.tabs(["💡 Smart Suggestions", "🎨 Style Fixes", "💬 Ask AI"])

        with tab_main:
             # Split response into parts
             parts = st.session_state.ai_review.split("## Improved Code")
             pre_code_text = parts[0]
             
             # Looking for the detailed explanations which come after the code block
             post_code_text = ""
             # Check for Detailed Explanations section explicitly
             expl_match = re.search(r"## Detailed Explanations(.*?)$", st.session_state.ai_review, re.DOTALL)
             if expl_match:
                 post_code_text = expl_match.group(1).strip()

             # 1. Show Summary & Issues (Pre-Code)
             st.markdown("### 🔍 Code Review Insights")
             st.write_stream(stream_data(pre_code_text))

             # 2. Extract and Show Diff
             corrected_code = extract_corrected_code(st.session_state.ai_review)
             if corrected_code:
                 st.markdown("---")
                 st.markdown("### ⚖️ Side-by-Side Comparison")
                 diff_html = generate_diff_view(st.session_state.code_input, corrected_code)
                 st.components.v1.html(diff_html, height=400, scrolling=True)
                 
                 # Show Copyable Code
                 with st.expander("📋 View Corrected Code Block"):
                     st.code(corrected_code, language="python")

             # 3. Show Detailed Explanations (Post-Code)
             if post_code_text:
                 st.markdown("---")
                 st.markdown("### 📝 Detailed Explanations")
                 st.write_stream(stream_data(post_code_text))

             st.markdown("---")
             
             col_regen, col_download = st.columns(2)
             
             with col_regen:
                 if st.button("🔄 Regenerate Review"):
                     with st.spinner("Regenerating..."):
                         st.session_state.ai_review = get_code_suggestions(st.session_state.code_input)
                         st.rerun()
             
             with col_download:
                 # Generate Report Content
                 report_content = f"""# AI Code Review Report
**Date:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## 💻 Source Code
```python
{st.session_state.code_input}
```

## 📊 Analysis Status
- **Syntax Errors:** {'Yes' if st.session_state.errors else 'No'}
- **Static Issues:** {len(st.session_state.get("static_warnings", []))}

"""
                 if st.session_state.errors:
                     report_content += f"\n## ❌ Syntax Errors\n{st.session_state.errors}\n"
                 
                 if st.session_state.get("static_warnings"):
                     report_content += "\n## ⚠️ Static Warnings\n"
                     for w in st.session_state.static_warnings:
                         report_content += f"- {w['type']}: {w['message']}\n"

                 report_content += f"\n## 💡 AI Suggestions\n{st.session_state.ai_review}"

                 st.download_button(
                     label="📥 Download Report",
                     data=report_content,
                     file_name=f"code_review_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.md",
                     mime="text/markdown"
                 )
        
        with tab_style:
             st.markdown("### 🧹 Auto-Formatted Code (PEP 8)")
             if st.session_state.get("style_result"):
                 st.code(st.session_state.style_result, language="python")
                 st.caption("This code has been automatically formatted to standard python guidelines.")
             else:
                 st.info("No style corrections needed or available.")

        with tab_chat:
            st.markdown("### 🤖 Ask about your code")
            if "chat_history" not in st.session_state:
                st.session_state.chat_history = []

            for message in st.session_state.chat_history:
                with st.chat_message(message["role"]):
                    st.markdown(message["content"])

            if prompt := st.chat_input("Ask a question about the code..."):
                st.session_state.chat_history.append({"role": "user", "content": prompt})
                with st.chat_message("user"):
                    st.markdown(prompt)

                with st.chat_message("assistant"):
                    with st.spinner("Thinking..."):
                        response = ask_code_question(st.session_state.code_input, prompt)
                        st.markdown(response)
                        st.session_state.chat_history.append({"role": "assistant", "content": response})

    else:
        st.info("👋 No analysis found. Go to **Code Studio** to start.")

def render_history():
    """Renders the Session History page."""
    st.markdown('<div class="main-header">Session History</div>', unsafe_allow_html=True)
    
    if "history" not in st.session_state:
        st.session_state.history = []

    st.markdown(f"**Total Analyses in this Session:** {len(st.session_state.history)}")
    
    if not st.session_state.history:
        st.info("No history yet. Run some analyses!")
    
    for i, item in enumerate(st.session_state.history):
        with st.expander(f"📅 {item['timestamp']} - {item['code'].splitlines()[0][:50]}..."):
            st.caption(f"Errors Detected: {'Yes' if item['errors'] else 'No'}")
            
            t1, t2 = st.tabs(["Code", "Review Report"])
            with t1:
                st.code(item['code'], language="python")
            with t2:
                st.markdown(item['review'])
            
            if st.button(f"Load this into Editor", key=f"load_{i}"):
                st.session_state.code_input = item['code']
                st.session_state.ai_review = item['review']
                st.session_state.errors = item['errors']
                st.session_state.static_warnings = item.get('warnings', [])
                st.success("Loaded! Go to Insights tab.")
